pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]

# ---------
# Kickstarter specific settings
#
# Basics
#
# 0. Page title and theme
title:            Shadows of Los Angeles
theme:            basic
#
# 1. Your website ( could be same as this page - see below )
website:          http://www.wagglebuttproductions.com
#
# 2. URL of this page
url:              http://jllong.github.io/
#
# 3. About your kickstarter project
project:
  #
  # Name of the project
  name:           Shadows of Los Angeles
  #
  # URL of the project. Use short urls to ensure you track the visits (Optional)
  url:            http://kck.st/1jkHVbk
  #
  # URL of a cover photo of your project
  cover_image:    http://s3.amazonaws.com/ksr/assets/001/596/432/02667caeb3eef81364d3258c33fba432_large.jpg?1391513897
  #
  # Use a one-liner to describe your project
  description:    A creature of legend stalks the shadows of Los Angeles, and only a small band of heroes can stop it.
#
# 4. Your Twitter handle
twitter_handle:   shadowsofla
#
# 5. Your Google analytics ID (Optional)
google_analytics: 
#
# 6. Welcome text, add <br /> to break lines
welcome_text:
  I've been dreaming of making this short film for years. Now, thanks to you and Kickstarter, it can become a reality. After watching F.W. Murnau_s Nosferatu, my friend and I were excited to do a movie old-school. I thought, What if I could tell that story in a more modern setting but preserve its dark side?

Shadows of Los Angeles is that movie. Our tale takes place in 1930s Los Angeles, and we are working with industry professionals to get the period's look and feel just right.
